{
 "title": "Solar Inverter Dashboard",
 "description": "Kostal Solar Electric Inverter Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Home Consumption",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt", "label": "Watt" }
   ],
   "targets": [
    { "expr": "devices_local_home_own_p", "legendFormat": "Own Consumption" },
    { "expr": "devices_local_home_bat_p", "legendFormat": "Battery" },
    { "expr": "devices_local_home_grid_p", "legendFormat": "Grid" },
    { "expr": "devices_local_home_pv_p", "legendFormat": "PV" },
    { "expr": "devices_local_home_p", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Input DC1 Power",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "devices_local_pv1_p" }
   ]
  },
  {
   "title": "Input DC2 Power",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "devices_local_pv2_p" }
   ]
  },
  {
   "title": "Battery Charging Cycles",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "devices_local_battery_cycles" }
   ]
  },
  {
   "title": "PV Generator Amperage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    { "expr": "devices_local_pv1_i", "legendFormat": "Input DC1 Amperage" },
    { "expr": "devices_local_pv2_i", "legendFormat": "Input DC2 Amperage" }
   ]
  },
  {
   "title": "PV Generator Power",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt", "label": "Watt" }
   ],
   "targets": [
    { "expr": "devices_local_pv1_p", "legendFormat": "Input DC1 Power" },
    { "expr": "devices_local_pv2_p", "legendFormat": "Input DC2 Power" },
    {
     "expr": "devices_local_pv1_p + devices_local_pv2_p",
     "legendFormat": "Input Total Power"
    }
   ]
  },
  {
   "title": "PV Generator Voltage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    { "expr": "devices_local_pv1_u", "legendFormat": "Input DC1 Voltage" },
    { "expr": "devices_local_pv2_u", "legendFormat": "Input DC2 Voltage" }
   ]
  },
  {
   "title": "Powermeter Frequency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "yaxes": [
    { "format": "hertz", "label": "Hz" }
   ],
   "targets": [
    {
     "expr": "devices_local_powermeter_frequency",
     "legendFormat": "Powermeter Frequency"
    }
   ]
  },
  {
   "title": "AC Frequency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "yaxes": [
    { "format": "hertz", "label": "Hz" }
   ],
   "targets": [
    { "expr": "devices_local_ac_frequency", "legendFormat": "AC Frequency" }
   ]
  },
  { "title": "Battery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Battery Charging Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "devices_local_battery_soc", "legendFormat": "Battery Charging Status" }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "devices_local_battery_u", "legendFormat": "Battery Voltage" }
   ]
  },
  {
   "title": "Battery Power",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    { "expr": "devices_local_battery_p", "legendFormat": "Battery Power" }
   ]
  },
  { "title": "Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Statistic Autarky Day",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "statistic_autarky_day", "legendFormat": "Autarky Day" }
   ]
  },
  {
   "title": "Statistic CO2 Saving Day",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "yaxes": [
    { "format": "masskg" }
   ],
   "targets": [
    { "expr": "statistic_co2saving_day/1000", "legendFormat": "CO2 Saving Day" }
   ]
  },
  {
   "title": "Statistic Energy Home Day",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "statistic_energy_home_day", "legendFormat": "Energy Home Day" }
   ]
  },
  {
   "title": "Statistic Own Consumption Rate Day",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "statistic_own_consumption_rate_day",
     "legendFormat": "Own Consumption Rate Day"
    }
   ]
  }
 ]
}