{
 "title": "Solar Inverter Dashboard",
 "description": "Kostal Solar Electric Inverter Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Inverter State",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    { "expr": "devices_local_inverter_state", "legendFormat": "Inverter State" }
   ]
  },
  {
   "title": "Main",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Home Consumption",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt", "label": "Watt" }
   ],
   "targets": [
    { "expr": "devices_local_home_own_p", "legendFormat": "Own Consumption" },
    { "expr": "devices_local_home_bat_p", "legendFormat": "Battery" },
    { "expr": "devices_local_home_grid_p", "legendFormat": "Grid" },
    { "expr": "devices_local_home_pv_p", "legendFormat": "PV" },
    { "expr": "devices_local_home_p", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Home Consumption (migrated)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "devices_local_home_own_p", "legendFormat": "Own Consumption" },
    { "expr": "devices_local_home_bat_p", "legendFormat": "Battery" },
    { "expr": "devices_local_home_grid_p", "legendFormat": "Grid" },
    { "expr": "devices_local_home_pv_p", "legendFormat": "PV" },
    { "expr": "devices_local_home_p", "legendFormat": "Total" }
   ]
  },
  {
   "title": "PV Generator Power",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt", "label": "Watt" }
   ],
   "targets": [
    { "expr": "devices_local_pv1_p", "legendFormat": "Input DC1 Power" },
    { "expr": "devices_local_pv2_p", "legendFormat": "Input DC2 Power" },
    {
     "expr": "devices_local_pv1_p + devices_local_pv2_p",
     "legendFormat": "Input Total Power"
    }
   ]
  },
  {
   "title": "Input DC1 Power",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "devices_local_pv1_p" }
   ]
  },
  {
   "title": "Input DC2 Power",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "devices_local_pv2_p" }
   ]
  },
  {
   "title": "Battery Charging Cycles",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "devices_local_battery_cycles" }
   ]
  },
  {
   "title": "PV Generator Voltage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "yaxes": [
    { "format": "volt", "label": "Volt" }
   ],
   "targets": [
    { "expr": "devices_local_pv1_u", "legendFormat": "Input DC1 Voltage" },
    { "expr": "devices_local_pv2_u", "legendFormat": "Input DC2 Voltage" }
   ]
  },
  {
   "title": "PV Generator Amperage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    { "expr": "devices_local_pv1_i", "legendFormat": "Input DC1 Amperage" },
    { "expr": "devices_local_pv2_i", "legendFormat": "Input DC2 Amperage" }
   ]
  },
  {
   "title": "Powermeter Frequency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "yaxes": [
    { "format": "hertz", "label": "Hz" }
   ],
   "targets": [
    {
     "expr": "devices_local_powermeter_frequency",
     "legendFormat": "Powermeter Frequency"
    }
   ]
  },
  {
   "title": "Grid Power",
   "type": "graph",
   "description": "Power to (+)/from (-) the grid.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt", "label": "Watt" }
   ],
   "targets": [
    { "expr": "devices_local_grid_p * -1", "legendFormat": "Grid Power" }
   ]
  },
  {
   "title": "Battery",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Battery Charging Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "devices_local_battery_soc", "legendFormat": "Battery Charging Status" }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    { "expr": "devices_local_battery_u", "legendFormat": "Battery Voltage" }
   ]
  },
  {
   "title": "Battery Power",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    { "expr": "devices_local_battery_p", "legendFormat": "Battery Power" }
   ]
  },
  {
   "title": "Battery Amperage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "devices_local_battery_i" }
   ]
  },
  {
   "title": "Inverter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Inverter Output Power",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    { "expr": "devices_local_ac_inv_out_p" }
   ]
  },
  {
   "title": "Inverter Power",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    { "expr": "devices_local_ac_l1_p", "legendFormat": "Phase 1" },
    { "expr": "devices_local_ac_l2_p", "legendFormat": "Phase 2" },
    { "expr": "devices_local_ac_l3_p", "legendFormat": "Phase 3" }
   ]
  },
  {
   "title": "Inverter Amperage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    { "expr": "devices_local_ac_l1_i", "legendFormat": "Phase 1" },
    { "expr": "devices_local_ac_l2_i", "legendFormat": "Phase 2" },
    { "expr": "devices_local_ac_l3_i", "legendFormat": "Phase 3" }
   ]
  },
  {
   "title": "Inverter Voltage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    { "expr": "devices_local_ac_l1_u", "legendFormat": "Phase 1" },
    { "expr": "devices_local_ac_l2_u", "legendFormat": "Phase 2" },
    { "expr": "devices_local_ac_l3_u", "legendFormat": "Phase 3" }
   ]
  },
  {
   "title": "Inverter / AC Frequency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "yaxes": [
    { "format": "hertz", "label": "Hz" }
   ],
   "targets": [
    { "expr": "devices_local_ac_frequency", "legendFormat": "AC Frequency" }
   ]
  },
  {
   "title": "Statistics Day",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Autarky Day",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "statistic_autarky_day", "legendFormat": "Autarky Day" }
   ]
  },
  {
   "title": "Statistic CO2 Saving Day",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "yaxes": [
    { "format": "masskg" }
   ],
   "targets": [
    { "expr": "statistic_co2saving_day/1000", "legendFormat": "CO2 Saving Day" }
   ]
  },
  {
   "title": "Statistic Energy Home Day",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "statistic_energy_home_day", "legendFormat": "Energy Home Day" }
   ]
  },
  {
   "title": "Statistic Own Consumption Rate Day",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "statistic_own_consumption_rate_day",
     "legendFormat": "Own Consumption Rate Day"
    }
   ]
  },
  {
   "title": "Statistics Month",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Autarky Month",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "statistic_autarky_month" }
   ]
  },
  {
   "title": "CO2 Saving Month",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "yaxes": [
    { "format": "massg" }
   ],
   "targets": [
    { "expr": "statistic_co2saving_month", "legendFormat": "CO2 Saving" }
   ]
  },
  {
   "title": "Energy Home Month",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "statistic_energy_home_month" }
   ]
  },
  {
   "title": "Own Consumption Rate Month",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "statistic_own_consumption_rate_month"
    }
   ]
  },
  {
   "title": "Statistics Year",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 111 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Autarky Year",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "statistic_autarky_year" }
   ]
  },
  {
   "title": "CO2 Saving Year",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "yaxes": [
    { "format": "massg" }
   ],
   "targets": [
    { "expr": "statistic_co2saving_year" }
   ]
  },
  {
   "title": "Energy Home Year",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "statistic_energy_home_year" }
   ]
  },
  {
   "title": "Own Consumption Rate Year",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 120 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "statistic_own_consumption_rate_year"
    }
   ]
  },
  {
   "title": "Statistics Total",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 128 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Autarky Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "statistic_autarky_total" }
   ]
  },
  {
   "title": "CO2 Saving Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "yaxes": [
    { "format": "massg" }
   ],
   "targets": [
    { "expr": "statistic_co2saving_total" }
   ]
  },
  {
   "title": "Enery Home Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 137 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "statistic_energy_home_total" }
   ]
  },
  {
   "title": "Own Consumption Rate Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 137 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "statistic_own_consumption_rate_total"
    }
   ]
  }
 ]
}