{
 "title": "Solar Inverter Dashboard",
 "description": "Kostal Solar Electric Inverter Dashboard",
 "tags": [
  "Kostal",
  "Inverter",
  "Solar Energy",
  "Plenticore"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Energy Yield", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Energy Yield",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "max(statistic_yield_day offset -1d)",
     "legendFormat": "Energy Yield {{d}}"
    },
    {
     "expr": "max_over_time(statistic_yield_day{}[5m])",
     "legendFormat": "Energy Yield Current Day"
    }
   ]
  },
  {
   "title": "Energy Yield and Home Consumption Current Day",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "max_over_time(statistic_yield_day{}[1m])",
     "legendFormat": "Energy Yield Day"
    },
    { "expr": "statistic_energy_home_day", "legendFormat": "Home Consumption Total" },
    { "expr": "statistic_energy_home_pv_day", "legendFormat": "Home Consumption from PV" },
    { "expr": "statistic_energy_home_grid_day", "legendFormat": "Home Consumption from Grid" },
    { "expr": "statistic_energy_home_bat_day", "legendFormat": "Home Consumption from Battery" }
   ]
  },
  {
   "title": "Main",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Home Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "devices_local_home_own_p", "legendFormat": "Own Consumption" },
    { "expr": "devices_local_home_bat_p", "legendFormat": "Battery" },
    { "expr": "devices_local_home_grid_p", "legendFormat": "Grid" },
    { "expr": "devices_local_home_pv_p", "legendFormat": "PV" },
    { "expr": "devices_local_home_p", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Input Power PV",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "devices_local_pv1_p", "legendFormat": "DC1" },
    { "expr": "devices_local_pv2_p", "legendFormat": "DC2" }
   ]
  },
  {
   "title": "Inverter State",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    { "expr": "devices_local_inverter_state", "legendFormat": "Inverter State" }
   ]
  },
  {
   "title": "Battery Charging Cycles",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "devices_local_battery_cycles" }
   ]
  },
  {
   "title": "PV Generator Amperage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "devices_local_pv1_i", "legendFormat": "Input DC1 Amperage" },
    { "expr": "devices_local_pv2_i", "legendFormat": "Input DC2 Amperage" }
   ]
  },
  {
   "title": "PV Generator Power",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "devices_local_pv1_p", "legendFormat": "Input DC1 Power" },
    { "expr": "devices_local_pv2_p", "legendFormat": "Input DC2 Power" },
    {
     "expr": "devices_local_pv1_p + devices_local_pv2_p",
     "legendFormat": "Input Total Power"
    }
   ]
  },
  {
   "title": "PV Generator Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "devices_local_pv1_u", "legendFormat": "Input DC1 Voltage" },
    { "expr": "devices_local_pv2_u", "legendFormat": "Input DC2 Voltage" }
   ]
  },
  {
   "title": "Grid Power",
   "type": "timeseries",
   "description": "Power to (+)/from (-) the grid.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "devices_local_grid_p * -1", "legendFormat": "Grid Power" }
   ]
  },
  {
   "title": "Powermeter Frequency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "devices_local_powermeter_frequency",
     "legendFormat": "Powermeter Frequency"
    }
   ]
  },
  {
   "title": "Battery",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Battery Charging Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "devices_local_battery_soc", "legendFormat": "Battery Charging Status" }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "devices_local_battery_u", "legendFormat": "Battery Voltage" }
   ]
  },
  {
   "title": "Battery Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "devices_local_battery_p", "legendFormat": "Battery Power" }
   ]
  },
  {
   "title": "Battery Amperage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "devices_local_battery_i", "legendFormat": "Battery Amperage" }
   ]
  },
  {
   "title": "Inverter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Inverter Output Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "devices_local_ac_inv_out_p", "legendFormat": "Inverter Output Power" }
   ]
  },
  {
   "title": "Inverter Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "devices_local_ac_l1_p", "legendFormat": "Phase 1" },
    { "expr": "devices_local_ac_l2_p", "legendFormat": "Phase 2" },
    { "expr": "devices_local_ac_l3_p", "legendFormat": "Phase 3" }
   ]
  },
  {
   "title": "Inverter Amperage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "devices_local_ac_l1_i", "legendFormat": "Phase 1" },
    { "expr": "devices_local_ac_l2_i", "legendFormat": "Phase 2" },
    { "expr": "devices_local_ac_l3_i", "legendFormat": "Phase 3" }
   ]
  },
  {
   "title": "Inverter Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "devices_local_ac_l1_u", "legendFormat": "Phase 1" },
    { "expr": "devices_local_ac_l2_u", "legendFormat": "Phase 2" },
    { "expr": "devices_local_ac_l3_u", "legendFormat": "Phase 3" }
   ]
  },
  {
   "title": "Inverter / AC Frequency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    { "expr": "devices_local_ac_frequency", "legendFormat": "AC Frequency" }
   ]
  },
  {
   "title": "Statistics Day",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Autarky Day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "statistic_autarky_day", "legendFormat": "Autarky Day" }
   ]
  },
  {
   "title": "Statistic Own Consumption Rate Day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "statistic_own_consumption_rate_day",
     "legendFormat": "Own Consumption Rate Day"
    }
   ]
  },
  {
   "title": "Energy Yield Day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    { "expr": "statistic_yield_day", "legendFormat": "Energy Yield Day" }
   ]
  },
  {
   "title": "Statistic CO2 Saving Day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    { "expr": "statistic_co2saving_day/1000", "legendFormat": "CO2 Saving Day" }
   ]
  },
  {
   "title": "Statistic Energy Home Day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    { "expr": "statistic_energy_home_day", "legendFormat": "Home Consumption Total" }
   ]
  },
  {
   "title": "Home Consumption from PV",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    { "expr": "statistic_energy_home_pv_day", "legendFormat": "Home Consumption from PV" }
   ]
  },
  {
   "title": "Home Consumption from Battery",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    { "expr": "statistic_energy_home_bat_day", "legendFormat": "Home Consumptoin from Battery" }
   ]
  },
  {
   "title": "Home Consumption from Grid",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    { "expr": "statistic_energy_home_grid_day", "legendFormat": "Home Consumption from Grid" }
   ]
  },
  { "title": "Statistics Month", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 } },
  {
   "title": "Autarky Month",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "statistic_autarky_month", "legendFormat": "Autarky Month" }
   ]
  },
  {
   "title": "Statistic Own Consumption Rate Month",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "statistic_own_consumption_rate_month",
     "legendFormat": "Own Consumption Rate Month"
    }
   ]
  },
  {
   "title": "Energy Yield Month",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    { "expr": "statistic_yield_month", "legendFormat": "Energy Yield Month" }
   ]
  },
  {
   "title": "Statistic CO2 Saving Month",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    { "expr": "statistic_co2saving_month/1000", "legendFormat": "CO2 Saving Month" }
   ]
  },
  {
   "title": "Statistic Energy Home Month",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    { "expr": "statistic_energy_home_month", "legendFormat": "Home Consumption Total" }
   ]
  },
  {
   "title": "Home Consumption from PV",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    { "expr": "statistic_energy_home_pv_month", "legendFormat": "Home Consumption from PV" }
   ]
  },
  {
   "title": "Home Consumption from Battery",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "statistic_energy_home_bat_month",
     "legendFormat": "Home Consumptoin from Battery"
    }
   ]
  },
  {
   "title": "Home Consumption from Grid",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "statistic_energy_home_grid_month",
     "legendFormat": "Home Consumption from Grid"
    }
   ]
  },
  { "title": "Statistics Year", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 118 } },
  {
   "title": "Autarky Year",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "statistic_autarky_year", "legendFormat": "Autarky Year" }
   ]
  },
  {
   "title": "Statistic Own Consumption Rate Year",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "statistic_own_consumption_rate_year",
     "legendFormat": "Own Consumption Rate Year"
    }
   ]
  },
  {
   "title": "Energy Yield Year",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    { "expr": "statistic_yield_year", "legendFormat": "Energy Yield Year" }
   ]
  },
  {
   "title": "Statistic CO2 Saving Year",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    { "expr": "statistic_co2saving_year/1000", "legendFormat": "CO2 Saving Year" }
   ]
  },
  {
   "title": "Statistic Energy Home Year",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    { "expr": "statistic_energy_home_year", "legendFormat": "Home Consumption Total" }
   ]
  },
  {
   "title": "Home Consumption from PV",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    { "expr": "statistic_energy_home_pv_year", "legendFormat": "Home Consumption from PV" }
   ]
  },
  {
   "title": "Home Consumption from Battery",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    { "expr": "statistic_energy_home_bat_year", "legendFormat": "Home Consumptoin from Battery" }
   ]
  },
  {
   "title": "Home Consumption from Grid",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "statistic_energy_home_grid_year",
     "legendFormat": "Home Consumption from Grid"
    }
   ]
  },
  { "title": "Statistics Total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 135 } },
  {
   "title": "Autarky Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "statistic_autarky_total", "legendFormat": "Autarky Total" }
   ]
  },
  {
   "title": "Statistic Own Consumption Rate Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "statistic_own_consumption_rate_total",
     "legendFormat": "Own Consumption Rate Total"
    }
   ]
  },
  {
   "title": "Energy Yield Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    { "expr": "statistic_yield_total", "legendFormat": "Energy Yield Total" }
   ]
  },
  {
   "title": "Statistic CO2 Saving Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    { "expr": "statistic_co2saving_total/1000", "legendFormat": "CO2 Saving Total" }
   ]
  },
  {
   "title": "Statistic Energy Home Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 144 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    { "expr": "statistic_energy_home_total", "legendFormat": "Home Consumption Total" }
   ]
  },
  {
   "title": "Home Consumption from PV",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 144 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    { "expr": "statistic_energy_home_pv_total", "legendFormat": "Home Consumption from PV" }
   ]
  },
  {
   "title": "Home Consumption from Battery",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 144 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "statistic_energy_home_bat_total",
     "legendFormat": "Home Consumptoin from Battery"
    }
   ]
  },
  {
   "title": "Home Consumption from Grid",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 144 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "statistic_energy_home_grid_total",
     "legendFormat": "Home Consumption from Grid"
    }
   ]
  }
 ]
}